name: Daily NAV Checker

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 12:00 PM Nepal Time (UTC+6)
  workflow_dispatch:  # Allows manual runs from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run NAV Checker
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_IDS }}
        run: python check_nav.py
