name: NAV Checker

on:
  schedule:
    - cron: '0 6 * * *'  # runs daily at 6 AM UTC
  workflow_dispatch:

jobs:
  check-nav:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID_1: ${{ secrets.CHAT_ID_1 }}
      CHAT_ID_2: ${{ secrets.CHAT_ID_2 }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

     - name: Install dependencies
       run: pip install requests beautifulsoup4

      - name: Run NAV Checker
        run: python check_nav.py
